### PR TITLE
Improvement/ie11 demo

### LINKED ISSUE #26: Example page does not work in IE 11
For some reason, the example page is now broken in IE 11. This has an effect on other projects using this library as well. Let's figure out what's wrong there.

### PR DESCRIPTION
**Pull request by frontendphil**
Fixes #26

I've added a webpack setup that also works in IE 11

### CODE REVIEW

**Comment by gisaklement** [comment]
I can't reproduce the initial bug. ☹️

**Comment by frontendphil** [comment]
@gisaklement you're saying the currently deployed demo version opens in your IE 11?

**Comment by gisaklement** [comment]
yes

**Comment by mersocarlin** [comment]
very off-topic here: just wanted to say that I miss Wolfpack 😉

**Comment by gisaklement** [comment]
Mersocarliiiiiiiiin! We miss you too! 😄

**Comment by frontendphil** [comment]
You know @mersocarlin the times have changed. Remote from Ireland is probably not impossible anymore ;) Plus, we could use distribute your hiring bonus in the team and visit when this whole virus thing is over.

**Pull request merged**
