### PR TITLE
chore: replace webpack with vite and Karma with Cypress

### PR DESCRIPTION
**Pull request by Jianrong-Yu**
Changes in this PR:

* `webpack` is replaced to `vite` for both `demo` and `test`
* `Karma` is replaced to `Cypress` for test.
  * All test cases are updated for Cypress syntax

`circleci` configuration is also updated for Cypress.

### CODE REVIEW

**Comment by crecotun** [comment]
Hi @Jianrong-Yu 
I wanted to fix conflicts to test the PR, but then I committed my changes I got following error
```
.husky/pre-commit: line 4: npx: command not found
husky - pre-commit hook exited with code 127 (error)
```

All solutions are mentioned using NVM, which I don't have and would prefer not to have until I need it.
Do you know how to fix that?

**Comment by Jianrong-Yu** [comment]
> All solutions are mentioned using NVM, which I don't have and would prefer not to have until I need it. Do you know how to fix that?

@crecotun `npx` is installed with nodejs after v5.2. If it's gone there must be some issues on your nodejs installation. An reinstallation of nodejs or `npx` (mentioned in this answer: https://stackoverflow.com/a/51224061/18413603) should fix it.

BTW I've fixed the conflicts and it's ready for mering now. Please review it for merger approval.

**Review by crecotun — DISMISSED** [review]

**Comment by crecotun** [comment]
@Jianrong-Yu I have approved PR and enabled auto-merge
Could you please fix conflicts one more time? 😅

**Comment by Jianrong-Yu** [comment]
@crecotun The conflict is fixed, please review it again. BTW, I pushed another commit https://github.com/signavio/react-stick/pull/417/commits/9db2cb914bbf48dc82eca132bb7af5a771980293 to upgrade Cypress from v9 to v10, since the component test feature changes from experimental to beta in v10 (released on June 1, 2022), I think it's better to upgrade it since it changed a lot and should be more stable.

**Review by crecotun — APPROVED** [review]

**Pull request merged**
